# AppVeyor <https://ci.appveyor.com>

version: 2.0.{build}

image: Visual Studio 2019

environment:
  KNOWBUG_MSBUILD: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe"

build_script:
- ps: |
    ./scripts/build-all.ps1
    if (!$?) {
        exit 1
    }

test_script:
- ps: |
    ./scripts/test-all.ps1
    if (!$?) {
        exit 1
    }
